// AUTO-GENERATED by scripts/build-tv-manifest.mjs — do not edit by hand.
// Eligible images for the /tv signage route. Excludes provider profile and
// location images. Re-run via "npm run build" or "npm run dev" (prebuild/predev).

export const tvImages = [
  "/assets/assist-hero-poster.webp",
  "/assets/assist-specialist.webp",
  "/assets/assist-table.webp",
  "/assets/consultation-1.webp",
  "/assets/consultation-2.webp",
  "/assets/digital-brain.webp",
  "/assets/get-assessed.webp",
  "/assets/guide-247.webp",
  "/assets/guide-hero.webp",
  "/assets/guide-life.webp",
  "/assets/hero-poster.webp",
  "/assets/latest-science.webp",
  "/assets/meet-neuro.webp",
  "/assets/ongoing-partnership.webp",
  "/assets/providers-hero-poster.webp",
  "/assets/science-hero-poster-v2.webp",
  "/assets/video-visit-poster.webp",
  "/assets/what-to-expect-conversation.webp",
  "/assets/what-to-expect-hero.webp",
] as const;

export type TvImage = (typeof tvImages)[number];
